terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
    }
  }

  required_version = ">= 1.5.0"
}

resource "local_file" "generated_demo" {
  filename = "${path.module}/generated-demo.txt"
  content  = "This file is generated by Terraform."
}

output "generated_file" {
  description = "Path to the generated file"
  value       = local_file.generated_demo.filename
}
